### ISSUE TITLE
Render RFC references

### ISSUE THREAD

**Issue by andrew2net** [riboseinc/asciidoctor-rfc#101]
@opoudjis I didn't find in examples reference like in asciidoctor-iso
```
* [[[iso123,ISO 123]]] _Standard_
```
do we need to add rendering such refs?
If yes, suppose the place to implement the functional is `ref_section(node)` function in `/asciidoctor-rfc/lib/asciidoctor/rfc/v3/base.rb`. Do you agree?

**Comment by opoudjis** [comment]
Your question is, where is bibliography building handled in RFC. The answer is that they are indeed handled in ref_section(); and asciidoctor-rfc already has functionality to query the RFC bibliographic database and add references: common/base.rb, cache_biblio() and insert_biblio(). No functionality needs to be added to asciidoctor-rfc.

Hypothetically, we could add isobib functionality to asciidoctor-rfc; that would necessitate translating Relaton XML to RFC XML. In practice, let's not do that unless Ronald asks for it; it will make things messier, and RFC documents don't cite outside of the IETF often enough for it to add much value.

**Comment by opoudjis** [comment]
The two bibliographies of ISO and rfc I fixed completely differently, and serialised completely differently. If we keep the two separate, conflating some in the one gem is not useful. if we attempt to merge them, but somehow mapping rfc bibliographies that are already in the correct format into Relaton XML and back, it is even less useful.

**Comment by andrew2net** [comment]
@ronaldtse I finished RfcBib gem. If we shouldn't integrate it into asciidoctor-rfc, when what is next step?

**Comment by opoudjis** [comment]
It is intended for integration into asciidoctor-iso and asciidoctor-gb. I will assign myself tickets to do so.

**Comment by ronaldtse** [comment]
The other part is to refactor asciidoctor-rfc into the same structure as asciidoctor-iso and asciidoctor-gb, but it's separate from this ticket.

**Comment by ronaldtse** [comment]
(https://github.com/riboseinc/asciidoctor-rfc/issues/105)
