### ISSUE TITLE
In RFC style, backticks should be presented as double quotes

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#103]
From RFC Editor.

**Comment by opoudjis** [comment]
I do not understand this ticket.

**Comment by ronaldtse** [comment]
RFC editor said in feedback:

> c) We see quite a few instances of the " ` " character used in the
text of this document and in some lines of code.  Are these
"smart quotes"?

This template requires usage of the `asciidoctor-rfc` Ruby gem.
(We see that draft-asciirfc-minimal-02 has
"This template requires usage of the "asciidoctor-rfc" Ruby gem.")

monospace: "`type`"
"type"
`description`
`details`
`parameters`
`asciidoctor-rfc` Ruby gem
"asciidoctor-rfc" gem in Ruby
asciidoctor-rfc Ruby gem

The backpack (`) is intended as the Asciidoc marker for monospace text. Following RFC practice, this should be substituted with “ “ in text, and with <spanx style=“verb”> in the underlying RFC XML.

**Comment by ronaldtse** [comment]
Phew, the above comment corrected.

**Comment by opoudjis** [comment]
There should be no "`" in the RFC XML output; if there are, they are a bug. My impression is that the editors were simply unfamiliar with the "`" convention of Asciidoctor. If there is no "`" in the RFC XML, there is nothing to fix.

**Comment by ronaldtse** [comment]
I think they were concerned with the back-ticks in the content of the RFC, not those in the actual raw quotations?

**Comment by opoudjis** [comment]
I've just regenerated the XML for the RFC draft (RFC XML v2, which is what they saw), and the *only* instances of backtick in the XML are in quotations of Asciidoctor. Where backticks are in unquoted Asciidoc, meaning monospace, they are being converted correctly to `<span style="verb">`. I'm not seeing anything to fix.

**Comment by ronaldtse** [comment]
Excellent, thanks!
