### ISSUE TITLE
Support "section" references like MMark

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#12]
In normal AsciiDoc a section reference will produce the title.

In RFCs, a section reference should produce something like "Section 5.4.3".

In MMark, references like:
```
See Section (#header)
```
Will produce `See Section 5.4.3`.

**Comment by opoudjis** [comment]
I will need help with this, @paolobrasolin , since my impression was that Asciidoc didn't quite do this with its xrefstyle, and I could be wrong.

**Comment by opoudjis** [comment]
This is not relevant to the RFC XML output of the gem: the gem, just like MMark, produces the output `<xref target="header"/>`. It is xml2rfc that ends up inserting section numbers. (And it does.)
