### ISSUE TITLE
XMLRFC v3: Validate Asciidoc v3 converter output against RFC XML v3 schema

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#14]

**Comment by opoudjis** [comment]
Converted .rnc schema to rng (XML format), which Nokogiri understands

**Comment by opoudjis** [comment]
Running RelaxNG validation for all output. The SVG validator is four times the size the validator of the RFC itself; but I guess we need to keep svg in there.

**Comment by opoudjis** [comment]
I'm keeping the ticket open, because it's finding unwelcome issues.

**Comment by opoudjis** [comment]
rspecs now pass validation.
