### ISSUE TITLE
XMLRFC v3: Make Asciidoc v2 and v3 converter input documentation friendlier

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#15]

**Comment by opoudjis** [comment]
#39 is the bulk of this ticket; leaving this ticket here in case I need to branch out to Github wiki.

**Comment by ronaldtse** [comment]
@opoudjis I think we should keep all of that in the README instead of Wiki, it's much clearer to read in the README.
