### ISSUE TITLE
XMLRFC v2: Validate Asciidoc v2 converter output against RFC XML v2 schema

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#19]

**Comment by opoudjis** [comment]
Converted .rnc schema to rng (XML format), which Nokogiri understands. Running RelaxNG validation for all output.

**Comment by opoudjis** [comment]
I'm keeping the ticket open, because it's finding unwelcome issues.

**Comment by opoudjis** [comment]
rspecs now all pass validation
