### ISSUE TITLE
XMLRFC v2: Convert rfc-openpgp-oscca Asciidoc to RFC XML v2

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#22]

**Comment by ronaldtse** [comment]
Here it is: https://github.com/riboseinc/rfc-openpgp-oscca-adoc

**Comment by opoudjis** [comment]
Have done so (attached output to Ribose discussion space); output will change with debugging and feature enhancements, but the spike here has been driven.
