### ISSUE TITLE
XMLRFC v2: Push Asciidoc v2 converter output of ref-openpgp-oscca through to rfc2xml, rfc2html, rfc2md

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#23]

**Comment by opoudjis** [comment]
I've had to remove three instances of non-Ascii characters:
* Two instances of Unicode minus sign, replaced with dash
* One line with em-dashes in references.

**Comment by ronaldtse** [comment]
@opoudjis could you let me know which lines caused these? Thanks!

**Comment by opoudjis** [comment]
Minuses: 08-sm2-kdf.adoc, 

```
    Ha! = MSB(KEYLEN - (v x Floor(n)), Ha_{Ceil(n)})
```

and 

```
  K = Ha_1 || Ha_2 || ... || Ha_{Ceil(n)-1} || Ha!
```

Em-dashes: 
```
    <title>ISO/IEC 14888-3:2016-03 -- Information technology -- Security techniques -- Digital signatures with appendix -- Part 3: Discrete logarithm based mechanisms</title>
```

As I've also noted, I've had to add in references for RFC and Internet Drafts referenced.

And xml2rfc is unhappy about:

```
WARNING: no <xref> in <rfc> targets <reference anchor='SM2-1'>
WARNING: no <xref> in <rfc> targets <reference anchor='GMT-0009-2012'>
WARNING: no <xref> in <rfc> targets <reference anchor='SM2-Template'>
````

**Comment by opoudjis** [comment]
Successfully pushed output through xml2rfc

**Comment by opoudjis** [comment]
And this is how the XML, HTML and TXT outputs looks.

[draft-openpg-oscca.zip](https://github.com/riboseinc/asciidoctor-rfc/files/1364350/draft-openpg-oscca.zip)

**Comment by ronaldtse** [comment]
Thanks @opoudjis ! I'm going to update the draft...

**Comment by opoudjis** [comment]
And there is .md output as well (hadn't gotten to this): attached.
[draft-openpgp-oscca.md.zip](https://github.com/riboseinc/asciidoctor-rfc/files/1392755/draft-openpgp-oscca.md.zip)

There are discrepancies between the source markdown and the produced markdown that I am now investigating.

**Comment by opoudjis** [comment]
Cleaned up a few rfc2md discrepancies.
