### ISSUE TITLE
AsciiDoc type header author syntax

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#24]
We currently support author attributes syntax like this:

```
= Title
Author One <author1@author.com>, Author Two <author2@author.com>
:organization: Author1 Org
:email: author1@author.com
:phone: (123) 456-7890
:street: 1, 1 Street
:city: One City
:region: OC
:code: 12345
:country: United States of America
:link: http://author.com/~author1
:organization_2: Author2 Org
:email_2: author2@author.com
...
```

But obviously this is very messy.

Of course, AsciiDoc (and asciidoctor) does not natively support Author Attributes, but we got to make one for XMLRFC.

The corresponding markup in MMark is this:
```
[[author]]
initials = "A."
surname = "One"
fullname = "Author 1 One"
organization = "Author1 Org"
  [author.address]
  email = "author1@author.com"
  uri = "http://author.com/~author1"
    [author.address.postal]
    street = "1, 1 Street"
    city = "One City"
    region = "OC"
    code = "12345"
    country = "United States of America"
```

Could we could use an asciidoctor-like Preprocessor Directive syntax block like `ifdef::/endif::` like this?

```
rfc-author::begin[]
  :initials: A. O.
  :surname: One
  :fullname: Author One
  :organization: Author1 Org
  :address.email: author1@author.com
  :address.uri: http://author.com/~author1
  :address.phone: (123) 456-7890
  :address.postal.street: "1, 1 Street"
  :address.postal.city: "One City"
  :address.postal.region: "OC"
  :address.postal.code: "12345"
  :address.postal.country: "United States of America"  
rfc-author::end[]
```

**Comment by ronaldtse** [comment]
@paolobrasolin what do you think is the best way of dealing with this issue? Basically we need to insert multiple author "model" attributes for multiple authors in asciidoctor.

**Comment by ronaldtse** [comment]
@paolobrasolin do you have a better idea for defining such models in asciidoctor attributes? The thing is asciidoctor attributes do not support lists.

The alternative is using external blocks like [Front Matter](http://asciidoctor.org/docs/user-manual/#front-matter-added-for-static-site-generators)
```
---  
front-matter-key: front-matter-data
---  
= Document Title

content
```

Look at this for example:
* https://raw.githubusercontent.com/asciidoctor/asciidoctor-extensions-lab/master/lib/front-matter-preprocessor/sample.adoc

**Comment by opoudjis** [comment]
And we are indeed considering that YAML solution for #86. I have to say, I prefer the native Asciidoc solution for authors, since it will render out of the box for downstream Asciidoc processors, which other solutions would not.

**Comment by ronaldtse** [comment]
I totally agree with the native AsciiDoc-type syntax for authors. The out-of-band YAML solution is too strange.

**Comment by ronaldtse** [comment]
@opoudjis can we conclude that unless we're using a different textual format, we won't be able to support a better author syntax? 😉

**Comment by opoudjis** [comment]
If we're playing nice with Asciidoc, YAML is the only way out of it, and YAML is not embedded in Asciidoc fully; so yes.

I mean, I could do an idiosyncratic solution of embedding YAML in the text proper—say the preamble, and fishing it out in parsing; but that kind of defeats the purpose of Asciidoc.
