### ISSUE TITLE
RFC style bibliography references

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#26]
@paolobrasolin XMLRFC supports bibliographic references like this (defined in [XMLRFCv2](https://tools.ietf.org/html/rfc7749) and [XMLRFCv3](https://tools.ietf.org/html/rfc7991)). Could we adopt this into a format that asciidoctor-bibliography supports?

```xml
<reference anchor='NIST.SP.800-56Ar2' target='http://dx.doi.org/10.6028/NIST.SP.800-56Ar2'>
  <front>
    <title>SP 800-56Ar2 Recommendation for Pair-Wise Key Establishment Schemes Using Discrete Logarithm Cryptography</title>
    <author initials="B." surname="Barker" fullname="Elaine B. Barker">
      <organization>National Institute of Standards and Technology</organization>
      <address>
        <postal>
          <street>100 Bureau Drive</street>
          <city>Gaithersburg</city>
          <region>MD</region>
          <code>20899</code>
          <country>United States</country>
        </postal>
        <uri>http://www.nist.gov/</uri>
      </address>
    </author>
    <author initials="L." surname="Chen" fullname="Lily Chen">
      <organization>National Institute of Standards and Technology</organization>
      <address>
        <postal>
          <street>100 Bureau Drive</street>
          <city>Gaithersburg</city>
          <region>MD</region>
          <code>20899</code>
          <country>United States</country>
        </postal>
        <uri>http://www.nist.gov/</uri>
      </address>
    </author>
    <author initials="A." surname="Roginsky" fullname="Allen Roginsky">
      <organization>National Institute of Standards and Technology</organization>
      <address>
        <postal>
          <street>100 Bureau Drive</street>
          <city>Gaithersburg</city>
          <region>MD</region>
          <code>20899</code>
          <country>United States</country>
        </postal>
        <uri>http://www.nist.gov/</uri>
      </address>
    </author>
    <author initials="M." surname="Smid" fullname="Miles Smid">
      <organization>Orion Security Solutions, Inc.</organization>
      <address>
        <postal>
          <street>1489 Chain Bridge Road</street>
          <street>Suite 300</street>
          <city>McLean</city>
          <region>VA</region>
          <code>22101</code>
          <country>United States</country>
        </postal>
        <uri>http://www.orionsecuritysolutions.com</uri>
      </address>
    </author>
    <date month='May' year='2013'/>
  </front>
</reference>
```

**Comment by ronaldtse** [comment]
BTW I'd like to add that MMark's supposedly citation syntax of `[@RFC1234, p. 123]` doesn't work as intended, all you get rendered is `[RFC1234]`.

**Comment by paolobrasolin** [comment]
I'll look into that. Off the top of my head I think the CSL schema (we're effectively using it) is a little smaller. Apart from that, serializing the data would not be a problem. (I saw a CSL style to directly render BibTeX, I think it'd be pretty straightforwart to write one to render to XMLRFC).

**Comment by opoudjis** [comment]
I'll note here that my attempt to convert ulist references into v3 refcontent elements has a fatal flaw: it skips the reference/front element, but the reference/front element, I've just  realised, is mandatory. (And there is no native Asciidoc way of realising the reference/front metadata, other than irritating microformatting.) 

So I'm jettisoning the attempt of converting ulist references, in v3, as more trouble than it's worth: you'd need to supply reference/front elements on top of any asciidoc conversion, and that would defeat any benefit the conversion of ulist would give.

**Comment by ronaldtse** [comment]
Indeed the front element is mandatory but it's just a container. I find it very strange that XMLRFC mixes the `rfc/front` with `reference/front` because they are so different for completely separate purposes.

I feel that there should be a data model for references that is a superset of XMLRFC's BIBXML and CSL.
