### ISSUE TITLE
Incorporating mathematical formatting in RFC XML output

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-rfc#27]
There's lots of mathematical formatting in MMark, delimited with $$, which I'm putting into Asciidoctor with the math[] macro. Maths is not natively supported by RFC XML. Should we presuppose an external XML schema for these, or leave them unrendered?

At a minimum, I could render it as italics, although I would have to selectively italicise only the letters and not the numbers or symbols in any such expression.

**Comment by ronaldtse** [comment]
I don't think the MMark math blocks are rendered specially, they seem to be just passed through as centered code blocks. We just need a nice way of representing them.

**Comment by opoudjis** [comment]
OK; just be aware that `<em>` will end up italicising numbers as well as letters in the Math markup, which is not strictly speaking correct. (But partially italicising numbers and not letters is even worse.)

**Comment by ronaldtse** [comment]
Ah ha, got it. Let's do it your way @opoudjis

**Comment by opoudjis** [comment]
... What *was* my way? :-) I think it's leaving them alone. It does look ugly, admittedly.

The real way of doing these is to embed them in an appropriate external schema, which a downstream processor can pay attention to or ignore. But whether that makes any sense to do at all is a matter of what IETF have in place!

The native ASCIIdoc way of doing things looks like it's ASCIIMathML (http://www1.chapman.edu/~jipsen/mathml/asciimathsyntax.html), which a processor converts to MathML—and we could do the same, but only if that's going to be useful downstream.

@ronaldtse, at the moment I'm leaving these alone then, but let me know if there would be any appetite over at IETF for dealing with MathML.

**Comment by ronaldtse** [comment]
Since the RFC XML schema doesn't specify specific support for Math, we probably shouldn't mess with that right now.

But it might be a good idea to have that option later to convert math to MathML output within XML (https://github.com/asciidoctor/asciidoctor-mathematical)

**Comment by opoudjis** [comment]
This issue does not need to be acted on in a hurry, since IETF does not say anything about Mathematical formatting yet; but I am already converting AsciiML to MathML for the asciidoctor-iso gem.

**Comment by opoudjis** [comment]
Closing this for now, since no indication that IETF can deal with math formatting; if they ask for this, we reactivate this (and it will be a straightforward task).
