### ISSUE TITLE
Rendering of table blocks

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#29]
MMark's handling of table blocks don't always work -- most of the time it is "supposed to fit" when seen in text, but then breaks out of the 72 char limit, eventually leaving most tables as hand-formatted ascii-tables.

We should make this work in our gem.

**Comment by opoudjis** [comment]
... The gem converts Asciidoc to RFC XML. The rendering of Asciidoc tables is up to the native Asciidoc renderers, and the rendering of RFC XML tables is up to RFC XML tools. So it's not clear to me what the gem should be doing. If a table overflows 72 characters, and that is a constraint to be obeyed in RFC markup, then the gem can only issue a warning if it sees that; it cannot chop the table up of its own initiative. @paolobrasolin , am I right?

**Comment by ronaldtse** [comment]
Yes you're right. The problem with MMark's RFCXML is an inaccurate representation of the <c> element often adding additional spaces causing the RFCXML-to-txt transformation to fail when it should succeed. Also, MMark does not support the table block format (which is the v3 way of writing out a table in Markdown).

In our gem, we should render AsciiDoc tables properly as RFCXML elements as accurate as possible.

**Comment by opoudjis** [comment]
OK. I'm happy to insert a warning at 72 characters in a row.
 
(Generally, some of the concerns you raise are taking me by surprise, because I'm not really taking MMark as a starting point! It may be that I'm trusting RFC XML too much...)

The added space is something I'll keep an eye on.

**Comment by opoudjis** [comment]
Added warning.

**Comment by ronaldtse** [comment]
Thanks @opoudjis !
