### ISSUE TITLE
Proper rendering of example / code blocks

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#30]
Code blocks in MMark are always centered unless given an attribute to not to.

However, if you have multiple code blocks (e.g., in ABNF) to demonstrate in a series, you will see very awkward centering of those code blocks so they are all in the middle. This feels very strange because code should alway start from the left side with some fixed indent.

The default behavior of our gem should left align the blocks with some minor indent that is configurable, centering should only be applicable to mathematical formulas, which should be centered.

**Comment by opoudjis** [comment]
As always, what the gem does with rendering is up to what is rendering the RFC XML it produces. There are align attributes  in figures and artwork, and they will default to left; so this should not be an issue; the onus will be on whoever is authoring the  Asciidoc to add a centering alignment where needed.

**Comment by opoudjis** [comment]
I'll have to see about configuring an indent; there's no provision for it natively in RFC XML.

**Comment by opoudjis** [comment]
MMark... seems to be taking a lot of liberties with the spec. :-)

**Comment by opoudjis** [comment]
Checked; the default behaviour of the gem is to leave the alignment unspecified, which xml2rfc does indeed treat as left aligned with an indent of 2.

The centering of mathematical formulas is handled as :stem, which currently is treated as identical to :literal; that means it will be left aligned. I will change it to make it :literal, but centered.
