### ISSUE TITLE
Supporting BCP14 (RFC 2119) keywords

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#31]
Some keywords are special in Internet Drafts / RFCs: "MUST", "MUST NOT", "SHOULD", etc.

These words are BCP14 keywords and must always be represented as uppercase "MUST". Our gem should detect these and ensure they are properly encoded in the XML within [`bcp14` tags](https://tools.ietf.org/html/rfc7991#section-2.9).

**Comment by opoudjis** [comment]
There is provision to mark these up in the Asciidoc for v3: `[bcp14]#MUST NOT#` will produce `<bcp14>MUST NOT</bcp14>`. I would be very wary of going further, and marking up automatically any instance of uppercase "MUST NOT" etc in the source. BCP14 is not supported in v2.

I do not believe anything further needs to be done with these.

**Comment by opoudjis** [comment]
... Could I confirm that's ok, @ronaldtse? Or do you want me to at least issue warnings if it finds either a BCP14 not in capitals, or a capital MUST not marked up as BCP14?

**Comment by ronaldtse** [comment]
Syntactically `[bcp14]#MUST NOT#` is fine but as you can see in every Internet-Draft or RFC, there are A LOT of them in every document. In MMark the star-star (sorry on mobile) syntax is used which is OK. It would be great if there is some shortcut syntax for BCP14 elements.

On the rfc-openpgp-oscca draft, remove the star-star from a keyword, compile it and run the `idnits` tool on the txt, you will see the various warnings including the "bcp14 keyword not marked" one.

**Comment by ronaldtse** [comment]
In v2 I believe bcp14 keywords must be capitalized too.

**Comment by opoudjis** [comment]
Merge this issue into #43
