### ISSUE TITLE
Attribute naming/retrieval

### ISSUE THREAD

**Issue by paolobrasolin** [riboseinc/asciidoctor-rfc#34]
The current attribute retrieval in the converter cannot work.
See http://asciidoctor.org/docs/user-manual/#attribute-restrictions

TL;DR: attributes are stored as lowercased.

We're retrieving them using ´camelCase` (i.e. their corresponding tag name). Therefore, we're retrieving `nil` on all attributes having a composite name.

I suggest we convert them to ´lowercase-dashed-case´ (attribute names allow only letters and dashes, with some exceptions for the first character, so this is standard practice for `asciidoctor`).

I'll do this on the way while I'm writing specs. Sounds good, @opoudjis?

**Comment by paolobrasolin** [comment]
Even better, I'll inject a dashified version of Rails' `underscore` in attribute getters.
https://apidock.com/rails/ActiveSupport/Inflector/underscore

**Comment by opoudjis** [comment]
Ah. OK; I will need to make sure that the attributes go to the right case in the XML output; so I'll tidy that up. Assigning issue to myself.

**Comment by ronaldtse** [comment]
Agree with the approach!

**Comment by paolobrasolin** [comment]
@opoudjis Ok. There should be no overhead (see the two commits referencing this issue).
