### ISSUE TITLE
Refactor common code between v2 and v3

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-rfc#37]

**Comment by opoudjis** [comment]
I'm proceeding with this now that both code versions are working, because it's going to get worse the longer I leave it. :-)

**Comment by paolobrasolin** [comment]
@opoudjis Sorry be the code cop but the new structure will bite us back fast and hard. Gonna do a bit of a cleanup and jot down a few guidelines to keep us on track.
