### ISSUE TITLE
Prettify README (and move to AsciiDoc)

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#39]
We probably should use tables for indicating v3/v2 asciidoc syntax equivalence to XMLRFC.

For syntax description, maybe we should mix v3/v2 and separate them according to purpose. For example, a separate section about "Front matter", "Abstract" so that duplicated syntax between v2 and v3 will just be shown once.

And README.md should really be README.adoc

**Comment by opoudjis** [comment]
Done. @ronaldtse , let me know if this is what you had in mind—and if not, how I can make it prettier.

**Comment by ronaldtse** [comment]
I've done some work on prettifying (8c143b9) and quite satisfied now 👍

**Comment by opoudjis** [comment]
Noticed your work, @ronaldtse :-) Looks like there's some residual cleanup to do, but it does read better now.

**Comment by ronaldtse** [comment]
@opoudjis please feel free to take it further, I’ve just notified the RFC editors of our work :wink.

**Comment by opoudjis** [comment]
Scary :)

OK, I'm still tuning things with the spec; once I've finished v2 and v3 I will clean up documentation. So reopening ticket.

**Comment by opoudjis** [comment]
Finalised documentation, and implemented the moves to make v2 and v3 consistent that @ronaldtse has put in documentation.
