### ISSUE TITLE
Define commands to insert RFC XML elements

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#4]
I think @opoudjis is most familiar with RFC XML elements and can come up with good examples 👍

**Comment by GildedHonour** [comment]
I've found a few examples, one in python, and learned it more or less. Now it makes more sense for me.

**Comment by opoudjis** [comment]
@ronaldtse, I don't understand what this ticket is asking for; is it asking for passthrough injecting of RFC XML into the Asciidoc? That's done by passthrough, using a `++++` delimiter. Or are you merely asking for sample Asciidoc?
