### ISSUE TITLE
Add remaining spec for v3, and for v2

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-rfc#41]

**Comment by opoudjis** [comment]
Hadn't even noticed there were specs already there! Am populating with alacrity; there are some bugs from Paolo's unrefactor, and I expect a lot more bugs from my own code.

**Comment by opoudjis** [comment]
This is going to take a while. I've already found I forgot to implement one v3 element, relref, although my implementation... well, it's a little baroque.

**Comment by paolobrasolin** [comment]
Take your time, do it right. 👍 
On a related note, I'm investigating how #33 can be solved (see branch `noko`).
I think this might be more than aesthetic: the code maintainability is greatly improved;
Also, I wrote a simple Nokogiri helper that willl allow us to transition seamlessly from plain test lists to full fledged Nokogiri in a really natural way, starting from the leafs of the RCF tree.

I already revised a couple of simple tags (trivial) and the `author` parsing tree. I think it's definitely worth it.

If you continue pushing specs as you write them, I can follow you and refactor the code nokifying it and ensuring it doesn't break.

**Comment by opoudjis** [comment]
@paolobrasolin , you are the wind beneath my wings. I have in fact used Nokogiri before, and I will be able to hammer out node rearranging when the time comes. I'm going to keep pushing the test cases out, and I'm trying to make them reasonably exhaustive.

**Comment by opoudjis** [comment]
Status: I have done all of v3 except for references. I have done none of v2.

Your nokogiri encoding of seriesInfo, which I did this morning, caught me by surprise, Paolo :-) —and I had modified the spec a little; but it's all good now.

**Comment by opoudjis** [comment]
Done all specs, v2 and v3

**Comment by paolobrasolin** [comment]
@opoudjis Excellent job! I'm nokifying the last remaining methods.
