### ISSUE TITLE
Automatic (normative/informative) references in AsciiDoc, should support output in both v2 and v3 formats

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#44]
It is understandable that some syntax is only acceptable by v2 and some only acceptable by v3.

However, the basic idea of the AsciiDoc is that it should be able to output in both formats regardless of the syntax used.

For example, in References there is a difference between AsciiDoc "v2 references" vs the "v3 references". Both should actually come from the same syntax. We can require the `asciidoctor-bibliography` gem to support this.

For RFC references like RFC1234 (or just the ones supported by xml2rfc as bibxml, see "Citation Libraries" on the [xml2rfc tool page](https://xml2rfc.tools.ietf.org/)), they do not need to be resolved -- they can be directly entered in into the XMLRFC and xml2rfc will resolve them.

See "Helpful Hints" on the same xml2rfc tool page:
```
<?xml version='1.0'?>
<!DOCTYPE rfc SYSTEM 'rfc2629.dtd' [
<!ENTITY rfc2629 PUBLIC '' 'http://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2629.xml'>
]>
...
<t>This document was constructed using the <xref target="RFC2629" /> DTD.</t>
...
<references>
...
&rfc2629;
...
</references>
```

There should be some automatic bibliography generation like this:
```
[[rfc-bibliography]]
```

**Comment by opoudjis** [comment]
If you do this, then you're either requiring that native Asciidoc references (in ulist format) not be supported by v3, because they will always expect rfc-bibliography output, or else you optionally enable ulist processing. So: if the contents of the bibliography are a ulist, the processor raises an error in v2, but it processes them in v3. 

Is that ok, or do you want to mandate rfc-bibliography in v3 as well?

**Comment by ronaldtse** [comment]
This seems to be about balancing flexibility (of fully utilizing the XMLRFC formats) or usability (of what most people expect when writing an Internet-Draft)?

The thing is native asciidoctor bibliography is it does not have any set model for a bibliography entry. The usage of `asciidoctor-bibliography` is supposed to implement that. XMLRFC references are supposed to be in `bibxml` format so the bibliographic entry data from the AsciiDoc must be convertible to it.

When I'm writing an internet-draft I'd rather not explicitly specify the reference groups.

So:
```
rfc-bibliography::[]
```

Is preferable to:

```
[bibliography]
= References

== Normative References
bibliography-group::[normative]

== Informative References
bibliography-group::[informative]
```

Is preferable to:

```
[bibliography]
= References

== Normative References
++++
<xml...>
++++

== Informative References
++++
<xml...>
++++
```

**Comment by opoudjis** [comment]
Looks like I have my answer. :) If there is a list in the bibliography, I'll process it under v3, but whether the bibliography is `bibliography-group::[normative]` or `+++ xml +++`, the converter is going to be seeing raw XML.

@paolobrasolin , can the bibliography-group::[] wrapper provide a `++++` wrapper, so the converter knows that what is coming out of it is raw xml?

**Comment by ronaldtse** [comment]
@opoudjis the only thing is that we don't have `bibliography-group:[]` yet in `asciidoctor-bibliography` 😉 .

However, since `bibxml` is a specific XML format that seem to be only used in RFCs, we could support rendering of `bibxml` output as an extension to `asciidoctor-bibliography` either in that gem or in this one. That said, the CSL model used by `asciidoctor-bibliography` does not seem to fully support the bibxml syntax. Let me create a new issue for this.
