### ISSUE TITLE
Per author attribute <street> supports multiple lines

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#46]
`:street{_i}:` could generate multiple lines if we use "," as a separator for its content, to generate multiple `<street>` elements.

**Comment by opoudjis** [comment]
No. The Asciidoc way of doing thing is by using "\ " to break up the attribute value into multiple lines, and that's already documented. We must not introduce idiosyncratic ways of doing things, and street lines will be full of commas anyway.

**Comment by ronaldtse** [comment]
You're right, forgot there are multiple commas. However, xml2rfc uses the `<street>` elements to create multiple address lines. In my references I always find it necessary to break into multiple `<street>` elements because sometimes the addresses are really long (e.g., academic institutions).

I don't think line breaks are properly rendered within a `<street>` element in xml2rfc?

**Comment by opoudjis** [comment]
As I said, this is catered for natively in Asciidoc, by the "\ " delimiter. This is already in rspec, spec/asciidoctor/rfc/v3/author_spec.rb:

```
      :docName:
      :street: 57 Mt Pleasant St\ Technology Park
      :city: Dullsville
      :region: NSW
      :country: Australia
      :code: 3333
```

converts to:

```
       <?xml version="1.0" encoding="UTF-8"?>
       <rfc preptime="1970-01-01T00:00:00Z"
                version="3" submissionType="IETF">
       <front>
       <title>Document title</title>
       <address>
       <postal>
       <street>57 Mt Pleasant St</street>
       <street>Technology Park</street>
       <city>Dullsville</city>
       <region>NSW</region>
       <code>3333</code>
       <country>Australia</country>
       </postal>
       <phone>555 5655</phone>
       <facsimile>555 5555</facsimile>
       <email>john.doe@email.com</email>
       <uri>http://example.com</uri>
       </address>
       </author>
       </front><middle>
       </middle>
       </rfc>
```

**Comment by ronaldtse** [comment]
This is nicely done indeed. Thank you!

**Comment by ronaldtse** [comment]
Since this works well could you help add this example to the README?

**Comment by ronaldtse** [comment]
I've updated it now.
