### ISSUE TITLE
Recreate RFC 6350 in the new AsciiDoc format

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-rfc#51]
From original REQUIREMENTS.adoc. @ronaldtse , please confirm this is still expected.

**Comment by ronaldtse** [comment]
No longer necessary. We’ve already got a better example.

**Comment by ronaldtse** [comment]
Actually, it’d be great to have a long example like this to exercise our code... how long do you think it’ll take to convert this?

**Comment by ronaldtse** [comment]
(An actual RFC not an internet draft)

**Comment by opoudjis** [comment]
Hm. 3-4 hrs?

**Comment by ronaldtse** [comment]
Let's do it 👍 Hope to make the flow work also for a published RFC.

**Comment by opoudjis** [comment]
Converted text; had some nifty nesting of definition lists.

Have not yet converted references.

**Comment by ronaldtse** [comment]
Thanks @opoudjis , it would be great if we could compare the generated RFC text (through `xml2rfc`) against the published one (we can include it in the `/spec` folder) so we know it is entirely (mostly) the same.

**Comment by opoudjis** [comment]
I will be doing an XML comparison with both this and #38. With xml2rfc, you're proposing a comparison of target formats from the two as well. OK, cool; do you want comparison of the HTML, or the TXT?

**Comment by ronaldtse** [comment]
Probably the HTML will catch more, but the TXT version will already tell us a lot. Let's first do TXT then HTML output comparison. For example in #59 a diff was run against the generated TXTs and found a number of issues.

**Comment by opoudjis** [comment]
I've done this, using the asciidoctor-bibliography gem. In order to do the TXT comparison, I am stripping out the page separations: it is impossible to get the pagination to aline, and I strongly suspect that the online RFC 6350 text file had manual line breaks inserted. There are also some occasional inexplicable variations in paragraph width, and hyphens do not seem to break at lines in the original. But after a lot of work, if we ignore line breaks, the texts do line up, and I have added RFC 6350 to the rspec. 

(The comparison of text output in general does not do well under rspec, because of differences in line breaks, but they are still very useful as examples.)

Having reconstructed the markup of 6350, btw, I am somewhat disappointed with how unadventurous it was originally; I would have used a lot more monospace, for example (which gets rendered as quotes in xml2rfc txt). The extensive definition lists now render correctly. Most tables align well, though one large table towards the end ends up with different table widths.
