### ISSUE TITLE
Shift cref to child of preceding paragraph

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-rfc#55]
As now noted in the Readme, the Asciidoc and RFC XML document models are different: paragraphs in Asciidoc do not straightforwardly contain other blocks the way they can in RFC XML. In particular, admonitions are separate blocks, whereas cref elements are assumed to belong to a paragraph.

For that reason, I propose to do postprocessing on the nokogiri, take any cref that is the child of a section (which is what happens now, and which is invalid for RFC XML), and make it the child of its preceding paragraph (where present). If no paragraph is present, it will be the child of an empty paragraph.

Objections or comments?

**Comment by ronaldtse** [comment]
@opoudjis I tend to agree that post-processing Nokogiri is easier than having them in the right structure on the outset. Your opinions @paolobrasolin ?

**Comment by opoudjis** [comment]
Done (fwiw); it's the cleanup() method in base.rb for both versions.
