### ISSUE TITLE
Are we force pushing on master?

### ISSUE THREAD

**Issue by abunashir** [riboseinc/asciidoctor-rfc#6]
Hi, @GildedHonour, I just came across this repo to find some of my recent work we did on this repo, but I don't see any of those changes like renaming the gem, adding missing standard ruby gem files and implementation of OSS guide. Did we change any plan on this gem and are we force pushing anything to the master?

Missing PR's - https://github.com/riboseinc/asciidoctor-rfc/pulls?q=is%3Apr+is%3Aclosed

**Comment by ronaldtse** [comment]
@abunashir we've not changed any plans and everything is as originally discussed. I don't think anyone should be force pushing to master.

**Comment by GildedHonour** [comment]
@abunashir 
yes. I have other projects that's why it's a bit slow, sorry. Also, it's taken a bit of time to learn what xml2rfc  is. I'll try to speed up. No change of the plan. 

But we haven't discussed in detail how we should commit. A new branch per issue? Or in the branch develop and then merge into master? I've pushed into master because there have been no other commits and developers. I'll then switch to develop, right?

Also we should rename the gem to rfc2xml or rfcxml, huh?

**Comment by ronaldtse** [comment]
@GildedHonour there were actually a number of commits from @abunashir already merged to master. As mentioned in issue #3, the gem is called "asciidoctor-rfc" as an asciidoctor backend.

**Comment by abunashir** [comment]
Regarding force pushing to master - I completely agree with @ronaldtse, we should never do that. Especially when we have multiple developers working on the project and we have open sourced the code. Rewriting git history in feature branch is okay, but we have to make sure we never do that to the `master` for any of our open source projects. 

@GildedHonour: We have the [details guideline here](https://github.com/riboseinc/oss-guides#general), including `Git Protocol`, `Best Practices ` and `Code Review`, please spent some time on those and if there is any question then ping @ronaldtse, me or @ribose-jeffreylau.

PS: I will try to restore those commits now, and once done then I will post another update here.

**Comment by abunashir** [comment]
I've restored the missing commits, and also extracted the additional work form @GildedHonour in #7. Please have look on those, I am not sure if those would be relevant but if necessary then maybe rebase and then merge that PR.

cc: @ronaldtse.
