### ISSUE TITLE
Output DTD is missing

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-rfc#60]
Child of #59 

`WARNING: No DTD given, defaulting to /usr/local/lib/python3.6/site-packages/xml2rfc/templates/rfc2629.dtd`

Do the sample documents from IETF have DTD link? 

Note that RFC 2629 is v1, but the DTD has been updated to v2. No idea if it has been updated to v3; rfc2xml not working for v3 yet.

**Comment by ronaldtse** [comment]
I read somewhere that v3 is using RNG so no more DTD.

**Comment by opoudjis** [comment]
Per examples in https://github.com/rfc-format , and https://www.ietf.org/archive/id/draft-hoffman-rfcexamples-04.txt, the minimum DTD link (which is still expected for v3) is:

````
<!DOCTYPE rfc SYSTEM 'rfc2629.dtd'>
````

Using the one DTD for v1, v2, v3 appears to be folly, but it's RFC's folly.

Examples do embed in the Doctype entities for referenced RFC references in RFC XML. I'd rather not do that, and have them all be handled consistently by acsiidoctor-bibliography. (However, acsiidoctor-bibliography should be using native RFC XML references over bibtex conversion, where the artefacts are available—as they are for RFCs.)

**Comment by ronaldtse** [comment]
Exactly RFC XML's folly... 

Regarding `embed in the Doctype entities for referenced RFC references in RFC XML`, perhaps we could also upgrade `asciidoctor-bibliography` to handle remote references...?

**Comment by opoudjis** [comment]
Suits me!

**Comment by opoudjis** [comment]
Added DTD to v2

**Comment by ronaldtse** [comment]
Any comments from @paolobrasolin ?

**Comment by opoudjis** [comment]
And v3
