### ISSUE TITLE
The "empty" list format is not supported in our gem yet

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-rfc#61]
Child of #59 

It is as far as I know; need to confirm.

**Comment by ronaldtse** [comment]
@opoudjis it still generates the "o" bullet in TXT format.

Here's the diff of our XML output and the empty RFC XML output:

Ours:
```xml
<t>Simple indented paragraph using the "empty" style:</t>
<t>
  <list style="symbols" hangIndent="8">
    <t>The quick, brown fox jumped over the lazy dog and lived to fool
many another hunter in the great wood in the west.</t>
  </list>
</t>
```

Working one:
```xml
<t>Simple indented paragraph using the "empty" style: <list
         hangIndent="10" style="empty">
<t>The quick, brown fox jumped over the lazy dog and lived to fool
many another hunter in the great wood in the west.</t>
</list></t>
```

**Comment by opoudjis** [comment]
The issue was Asciidoc attribute syntax. Any option attributes/positional attributes, with no value, such as "empty", need to appear first in the attribute list. Fixed in davies document.

**Comment by ronaldtse** [comment]
Ah ha, thanks @opoudjis !
