### ISSUE TITLE
Implement set_pis() for v3

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-rfc#64]
set_pis() implemented for v2; some of the defaulted options in v2 are configurable to document attributes in v3.

**Comment by opoudjis** [comment]
@ronaldtse, I am trusting your stated deviations about 

````
        # Below are generally applicable Processing Instructions (PIs)
        # that most I-Ds might want to use. (Here they are set differently than
        # their defaults in xml2rfc v1.32)
````

**Comment by ronaldtse** [comment]
This comment was lifted verbatim from:
https://github.com/riboseinc/asciidoctor-rfc/blob/master/spec/examples/davies-template-bare-06.xml.orig

We should definitely put a link to the davies template there. 👍
