### ISSUE TITLE
Spec comparison of RFC XML samples by TXT output

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-rfc#66]
````
bundle exec bin/asciidoctor-rfc2 spec/examples/davies-template-bare-06.adoc --trace; \
  xml2rfc spec/examples/davies-template-bare-06.xml -o new.txt; \
  xml2rfc spec/examples/davies-template-bare-06.xml.orig -o old.txt; \
  diff old.txt new.txt
````

**Comment by opoudjis** [comment]
Added first of many files to rspec; comparing only txt output for now.

**Comment by opoudjis** [comment]
There are spacing inconsistencies in the markdown files, but they are minor.

**Comment by opoudjis** [comment]
I introduced open block formatting to deal with the complex nested lists in RFC7511.

Major inconsistency with MMark output is that BCP14 output in MMark is just capitalised, whereas in current gem it is capitalised + strong: `SHOULD` vs `*SHOULD*`. Should I drop the boldfacing?

**Comment by ronaldtse** [comment]
I think we should do both boldface and capitalize :wink:

**Comment by opoudjis** [comment]
No problem. The MMark output in rspec is going to complain unnecessarily, since the MMark XML output does not do this, but better to make the discrepancy obvious.

**Comment by opoudjis** [comment]
... on second thought, I'm going to change the *BCP14* to BCP14 within the spec, for the purposes of comparison of the MMark outputs.

**Comment by ronaldtse** [comment]
Got it!

**Comment by opoudjis** [comment]
I am working on mitigating the spacing issues.

**Comment by opoudjis** [comment]
Mitigated as much as I can.

**Comment by ronaldtse** [comment]
Thank you @opoudjis . We just need to keep in mind that "mmark" is not technically the "authoritative" approach, but sticking to what it does is a good idea.

**Comment by opoudjis** [comment]
And indeed, there's a couple of areas where I've improved on MMark—notably in forcing use of the relref convention for addressing part of a reference. (It's v3, but I use it as a template for v2 as well.)

**Comment by ronaldtse** [comment]
@opoudjis could you help document those improvements so we all know what they are! 👍
