### ISSUE TITLE
Issues with newly created internet-draft

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#68]
@opoudjis I've run into some problems with this new ID: https://github.com/riboseinc/rfc-crypto-sm3

1. Author name cannot take a prefix, e.g., "Dr. X Y Z <email>" will get the email mangled.
2. "forename_initials" unable to set to more then one initial, such as "A. B."
3. "category" has to be set to v2 name such as "info" to pass v2 validation. 
4. I had a problem where the invalid XML generated gets damaged by the RELAXNG validator (because `puts` will cause it to actually write the error to the XML... strange, I've changed it to `$stderr.puts` and it works).
5. The "definition list" could be better formatted, such as by putting the value on the next line with the same indenting?
6. When the "definition list" keyword is a code word (e.g., wrapped by backticks), it shows this in txt: `<spanx style="verb">SS1</spanx>`.
7. How did you make XML references work? 😉

**Comment by ronaldtse** [comment]
It really took me a while to get this running properly...

**Comment by ronaldtse** [comment]
The generated TXT can be found here: https://github.com/riboseinc/rfc-crypto-sm3/releases/download/pre-02/draft-oscca-cfrg-sm3-02.txt

**Comment by ronaldtse** [comment]
I've just found out how to use the XML references, but the normative/informative citation thing isn't working yet.

The other annoyance is to have to manually download RFC XML references. Perhaps we could generate those using the RFC XML syntax of this for now?
```xml
<?rfc include="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml"?>
```

**Comment by opoudjis** [comment]
I'll get to this tonight.

The definitive RFC XML solution is supposed to be asciidoctor-bibliography; I can allow the passthrough of bibliography to pass through entity references, but I would then need to scan ahead and insert the entity references into the output, as you suggest. Is it worth doing that, or should the solution wait for  asciidoctor-bibliography?

**Comment by opoudjis** [comment]
`<spanx style="verb">SS1</spanx>` is how RFC XML v2 renders monospace ("verb" is for "verbatim"), so that bit is correct. v3 of course renders it as `<tt>`.

**Comment by ronaldtse** [comment]
@opoudjis the `spanx` output is somehow also passed through to the TXT though...

**Comment by opoudjis** [comment]
Fixing in order to regenerate locally: there was a repeated reference for WXY, and the reference for ISO.IEC.10118-3 was missing.

**Comment by opoudjis** [comment]
... Please give me permission to riboseinc/rfc-crypto-sm3.git ?

**Comment by opoudjis** [comment]
Author name not taking prefix is an Asciidoc API issue, which we can't fix; so I will put a warning in the README that, if you want to use anything other than given + middle + last name, you should not use the inline authors, but only the explicit author attributes.

**Comment by opoudjis** [comment]
3. Am mapping canonical v3 status names down to v2 categories: 

````
        category = node.attr("status")
        category = "info" if category == "informational"
        category = "std" if category == "standard"
        category = "exp" if category == "experimental"
````

Added to README.

**Comment by opoudjis** [comment]
4. Very surprised, since the `puts` were not getting into my xml output, but ok.

5. #69

**Comment by opoudjis** [comment]
7. The definition text under v2 is an attribute; for that reason, it is not allowed to have any formatting at all. This constraint is lifted in v3 for `<dt>`:

````
`Term`:: Definition
````

RFC XML v2: 

````
<t hangText="Term">Definition</t>
````

RFC XML 3
````
<dt><tt>Term</tt></dt>
<dd>Definition</dd>
````

I will strip out formatting from the v2 list term, as I'm already doing for `cref`.

**Comment by opoudjis** [comment]
Fixes done for the draft. I will push modifications to the .adoc once you grant me permission to.

**Comment by ronaldtse** [comment]
Thank you @opoudjis , you have access 👍

**Comment by ronaldtse** [comment]
Re 4. indeed I was surprised too, and I did double-check that the error messages were actually being written in the source file, causing it to be more invalid than it already was...

**Comment by ronaldtse** [comment]
Thank you also re. 7, that's a very subtle point!
