### ISSUE TITLE
idnits check over all XML2RFC output for sample files

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-rfc#71]

**Comment by opoudjis** [comment]
I see that idnits presupposes document type of internet-draft, it raises errors over the lack of an expiration date on an RFC proper.

**Comment by opoudjis** [comment]
... idnits really can't deal with old RFCs, so it won't be useful to incorporate into spec/examples

**Comment by ronaldtse** [comment]
In this case could we keep idnits to run on the Internet-Draft examples? Just not on the published RFCs. Thanks!
