### ISSUE TITLE
Add link to template repo `rfc-in-asciidoc-template`

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#76]
I've just made a template repo for creating new I-Ds / RFCs.

https://github.com/riboseinc/rfc-in-asciidoc-template

@opoudjis could you help update the README so that people who want to use the gem can directly clone / copy from this repo to start?

@paolobrasolin I think the new way of using a large XML file with all references could be broken down to individual files -- in this repo I included the "IncludeGlobProcessor" to allow the "*" file filter syntax for including all files in a directory. Could we somehow integrate that into `asciidoctor-bibliography`?

Thanks!

**Comment by opoudjis** [comment]
Done.

**Comment by ronaldtse** [comment]
Thanks @opoudjis !

**Comment by ronaldtse** [comment]
@paolobrasolin any thoughts on the above comment? Thanks!

**Comment by ronaldtse** [comment]
@paolobrasolin ping.

**Comment by ronaldtse** [comment]
@paolobrasolin ping again

**Comment by ronaldtse** [comment]
Now moved to https://github.com/riboseinc/asciidoctor-bibliography/issues/67.
