### ISSUE TITLE
AsciiRFC Internet-Draft bug

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#78]
I've just posted this: https://tools.ietf.org/html/draft-ribose-asciirfc-00

However, "Jeffrey Lau"'s full name is set wrongly at the end. This seems to me a bug in the renderer.

@opoudjis could you have a look at it? Thanks!

**Comment by opoudjis** [comment]
I have fixed this.

**Comment by ronaldtse** [comment]
Thank you @opoudjis !
