### ISSUE TITLE
RELAXNG validation error: <eref> inside <spanx>

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#79]
From https://github.com/riboseinc/rfc-asciidoc-rfc/issues/6.

This line input:

```
`:link: https ://en.wikipedia.org/wiki/Four_Yorkshiremen_sketch describedby`,
```

Causes an output of:

```
<spanx style="verb">:link: <eref target="https://en.wikipedia.org/wiki/Four_Yorkshiremen_sketch"/> describedby</spanx>,
```

Which is invalid in RFC XML.

Another example here:

```
`Tim Brooke-Taylor <tbt@bbc.co.uk>; John Cleese <jc@bbc.co.uk>`
```

Seems that the solution is just to not render any `<eref>` inside `<spanx>`?

**Comment by opoudjis** [comment]
Well, it's a nasty gotcha. I have fixed it by forcing the links not to render by escaping them, but yes, I will attempt to strip all markup from within a spanx span.

**Comment by opoudjis** [comment]
Done.

**Comment by ronaldtse** [comment]
Thanks @opoudjis , is the code pushed? Can't see it in commits...

**Comment by opoudjis** [comment]
Yes it is in the cleanup() routine in v2:

lib/asciidoctor/rfc/v2/base.rb, line 286:

````
# any instances of spanx must be stripped of any internal tags
        spanxs = xmldoc.xpath("//spanx[descendant::*]")
        while !spanxs.empty?
          spanx = spanxs[0]
          spanx_text = ""
          spanx.traverse do |node|
            spanx_text = spanx_text + node.text.gsub(/<[^>]+>/, "") if node.text?
          end
          spanx.children = spanx_text
          spanxs = xmldoc.xpath("//spanx[descendant::*]")
        end
````
