### ISSUE TITLE
Module name conventions

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#8]
@abunashir We should follow the asciidoctor extension module naming conventions. Thanks!

e.g.
https://github.com/riboseinc/asciidoctor-bibtex/blob/master/lib/asciidoctor-bibtex/asciidoctor.rb

**Comment by opoudjis** [comment]
I'm not currently using any extensions/macros that aren't built in, but I may not be understanding this. @paolobrasolin , if you understand this better, could you take this ticket over as part of your cleanup?

**Comment by paolobrasolin** [comment]
If this was part of the `asciidoctor` core it would live in `Asciidoctor::Converter::RFC2Converter` (et. anal. for v3).

The naming convention for extensions would be to name it `asciidoctor-rfc` and use the base namespace `Asciidoctor::RFC`. (`asciidoctor-bibtex` and `asciidoctor-bibliography` itself are non kosher, actually). Of course there is some variability, but that's what popular extensions seem to be doing.

On side note, I saw two `version.rb`, one for each api. I'm not particuarly convinced by that, (I'd go with one gem, one version). I'll open an issue about that when I'm actively refactoring.

@opoudjis Sure!

**Comment by opoudjis** [comment]
The two version.rb files are indeed wrong, and I was hoping you wouldn't notice. :-) There is no compelling reason to version v3 and v2 separately. Happy for you to get rid of this, or for me to.
