### ISSUE TITLE
Line numbers / file path missing in WARNING messages

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#82]
When running the RFCv2 backend, sometimes there are messages from lines like this:

```
warn "asciidoctor: WARNING (#{node.lineno}): header row of table is longer than 72 ascii characters" if rowlength > 72
```

However, `#{node.lineno}` is empty, so it is unclear which file / line the error is at. It seems that the node doesn't have `lineno` and `path` set when it was parsed by the `Reader`.

Any thoughts @opoudjis ?

**Comment by opoudjis** [comment]
Hm. Not all instances of node have lineno defined on them, it seems. Let me see if I can replicate this.

**Comment by opoudjis** [comment]
I can replicate it, and indeed, while all blocks have a lineno method, if their source_location attribute is not set, neither is their line number. (And I can't tell why a table's source_location attribute wouldn't be set in this case.)

As a mitigation, I'm going to give the current section title instead for all such warnings, wherever the line number is not available.

**Comment by opoudjis** [comment]
Done: Line number if available, else anchor of node, else current section title, else "??".
