### ISSUE TITLE
Uncertainty in allowed values of <workgroup> and <area>

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#83]
There is uncertainty regarding the allowed values of `<area>` and `<workgroup>`.

Currently @reschke 's `rfc2629.xslt` gives a warning like this:

For `<area>`:

> WARNING: Unknown IETF area: "internet" - should be one of: "Applications and Real-Time", "art", "General", "gen", "Internet", "int", "Operations and Management", "ops", "Routing", "rtg", "Security", "sec", "Transport", "tsv" (as of the publication date of 201711)

For `<workgroup>`:

> INFO: No need to include 'Working Group' or 'Research Group' postfix in /rfc/front/workgroup value 'Network Working Group'

However, [RFC7991](https://tools.ietf.org/html/rfc7991) leaves uncertainty in the actual allowed values and their representation.

Regarding `<area>`:

> Provides information about the IETF area to which this document relates (currently not used when generating documents).
> The value ought to be either the full name or the abbreviation of one of the IETF areas as listed on http://www.ietf.org/iesg/area.html A list of full names and abbreviations will be kept by the RFC Series Editor.

Regarding `<workgroup>`:

>  This element is used to specify the Working Group (IETF) or Research Group (IRTF) from which the document originates, if any. The recommended format is the official name of the Working Group (with some capitalization).
> In Internet-Drafts, this is used in the upper left corner of the boilerplate, replacing the "Network Working Group" string. Formatting software can append the words "Working Group" or "Research Group", depending on the "submissionType" property of the <rfc> element.

We should further clarify with (https://github.com/rfc-format/draft-iab-xml2rfc-v3-bis) on what these actual values should be.

Area:
* Should it be in full name or abbreviation? Could the RFC Series Editor provide their "full" list?
* In full name: according to the proper capitalization? Do we include the " Area" suffix in the value?

Workgroup:
* Should the suffix " Working Group" or " Research Group" be included in a submitted Internet-Draft?
* Should "(with some capitalization)" be "(with proper capitalization)"?

The best would certainly be a definite list exposed via API on the allowed values (i.e., working group names, area names), but minimally at least a clarification is necessary.

**Comment by opoudjis** [comment]
From the ensuing discussion, it looks like warnings should be issued, and that we accept both full names and abbreviations. From prior art, the word "Area" is omitted, and capitalisation should be as in the document, with nouns capitalised; I'll enforce this in the gem.

I'm reluctant to do much policing for Workgroups, since the list is much bigger and volatile, per https://datatracker.ietf.org/wg/ . I'd have thought you strip the suffix " Working Group" there too. I'm happy to warn about the suffix there, in any case.

I will eventually be manually looking at the xslt and porting across warnings, I suspect.

**Comment by opoudjis** [comment]
Have done fixed vocabulary in Area, allowing both abbreviations and full titles, and I eliminate suffixes from Workgroups and Areas. If there is no stable vocabulary of workgroups that can be looked up online, I will close this ticket.

**Comment by ronaldtse** [comment]
@opoudjis I agree that warnings should be issued instead of blocking errors.

The list of currently active groups can be found here (https://datatracker.ietf.org/wg/), the links that start with `https://datatracker.ietf.org/wg/{name}` are the WGs.

Concluded groups can be found here (https://datatracker.ietf.org/group/concluded/), the links that start with `https://datatracker.ietf.org/wg/{name}/about` are the WGs.

I suppose we could cache this for simplicity?

**Comment by opoudjis** [comment]
Implemented as cache `~/.asciidoc-rfc-workgroup-cache.json`, documented in README. I'm only doing active groups; a concluded group should be issuing a warning anyway.
