### ISSUE TITLE
Asciidoctor-biblio workaround

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-rfc#86]
We propose to do a workaround of Asciidoctor-biblio in asciidoctor-rfc, as follows. @ronaldtse, please modify the spec to match what you had in mind. We may end up splitting this up into tickets.

# Add a mechanism within Asciidoc to differentiate informative and normative references. 

Alternatives:

* The existing cite:norm[] and cite:info[] macros—but we need to ensure that they have all the flexibility that we have currently built in to `<< >>` (including our templates that deal with relref)
* More succinct macros for the two reference types. e.g. `[norm]#rfc2119#, [info]#w3c#`
* Macro for normative references, just `<<>>` for informative references. e.g. `[norm]#rfc2119#, <<w3c>>`
* Slight tweak of `<<>>` text for normative references. e.g. `<<!rfc2119>>, <<w3c>>` — the parser knows that `!` indicates normative. (This is pretty much what MMark does.)
* Just the pre-existing `<<>>` for both normative and informative references. Instead, we have a listing under document attributes of all the normative references (the user will know which ones are which), with informative being the default for any reference. e.g.

  :normative: rfc2119, rfc7991

  Because the <<rfc2119>> is listed among the normatives, it ends up in the normative listing.

My preferences is one of the last two. I gather you prefer the `<<!rfc2119>>` format, but I think `:normative: rfc2119, rfc7991` is much neater both for programming and conceptually.

# Directory of RFC XML references

Instead of a single file of RFC XML references, have a single directory of RFC XML references, named as a document attribute. Add support for referencegroups as a single RFC XML references. Do not have a bibliography section in the Asciidoc at all: the two separate bibliographies will be created by the gem, based on the normative/informative differentiation, and what has actually been cited, and sorted. Do not add any online bibxml entries to the directory, as they will be recognised from the anchor and included anyway.

# Modify gem to do reference filtering

That should be straightforward: each reference the gem sees (and it does see them) is added to a list of normative or informative references. (We filter out crossreferences to anchors in the document, so we need to track them too.) The external references are recognised by anchor and inserted as includes/entities; the remainder are fetched from the directory nominated. The gem creates a new normative and an informative references section, and inserts all the needed references there in post-processing.

Because we don't have a lot of information about the external references right now, we don't know enough to sort them alphabetically; but we can include author names in the scraping to address that.

**Comment by ronaldtse** [comment]
@opoudjis 

### Syntax

Among the alternatives the last one is definitely the easiest to use. This allows the user to not care about normative/informative when citing, and an easy switch if it is necessary to upgrade (I've had experience with "upgrading" an informative into a normative). The problem with the MMark-like syntax `<<!ref>>` is that the refs become inconsistent, some are `<<!norm-ref>>` while some are `<<norm-ref>>`.

### Directory of references

Agree with the approach. One thing though is that RFC XML allows extra reference groups in addition to "Informative" and "Normative", if we can support them it would be better, but if it is annoying we can ignore this for now.

### Reference filtering

Again this is a problem with the bib-item model. Given that all the input is in BibXML, it's probably better to write a separate "bibxml" gem that parses and sorts on those BibXML entries. This gem could then sort  using reference names, authors or other attributes. Then asciidoctor-rfc could utilize this gem as a dependency.

**Comment by opoudjis** [comment]
Implemented. At the moment it is in `biblio` branch of code. Sample below.

Referencegroups supported. Distinction between draft versions of I.D.s and generic I.D. references supported (by having a local I.D. reference file which links to a particular draft version, as before).

Not implementing sorting of references, since that is done in xml2rfc, and is specified as an attribute of RFC XML.

Right now the gem looks for the strings "Informative References" and "Normative References" in a `references` title or name, and splits the references two ways between them, with informative as default. We can introduce more reference groups in the document attributes, with informative remaining as the default; but (a) is this likely? (b) will xml2rfc deal with it at all? It will be a little annoying simply because asciidoc attributes aren't structured data, but there's no reason I can't jam a one-line JSON map into an attribute: `other-references: {Interesting References: [rfc0001, rfc0002], Annoying References: [mathjax, asciiimath]}

Right now the input is all in RFC XML :) . Having a dependency that iterates through a BibXML directory and generates a separate RFC XML directory is fine, it's just separate work.

But a combination of this implementation with such a gem (which *only* converts BibXML to RFC XML, and does not touch the Asciidoc) seems to me to obviate the need for asciidoctor-biblio completely in RFC processing. 

````
= The Holy Hand Grenade of Antioch
Arthur Pendragon
:doctype: internet-draft
:workgroup: silly
:normative: RFC2119, AsciiDoc
:biblio-insert: true
:biblio-dir: refs

[[xyz]]
== Hello
Hello

* a <<RFC2119,2.3 of: See internet draft subsection>>
* b <<I-D.abarth-cake>>
* c <<xyz,format=counter: xyzzy>>
* d <<biblio>>
* e <<AsciiDoc,AsciiDoctor>>


[[biblio]]
=== Biblio
See biblio

[bibliography]
== Normative References

[bibliography]
== Informative References
````

v2 output (note that referencegroup is not supported in v2, so validation complains):

````
<?xml version="1.0" encoding="US-ASCII"?>
<!DOCTYPE rfc SYSTEM "rfc2629.dtd" [
<!ENTITY RFC2119 SYSTEM "https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml">
<!ENTITY I-D.abarth-cake SYSTEM "https://xml2rfc.tools.ietf.org/public/rfc/bibxml3//reference.I-D.draft-abarth-cake-00.xml">
]>
<?rfc strict="yes"?>
<?rfc compact="yes"?>
<?rfc subcompact="no"?>
<?rfc toc="yes"?>
<?rfc tocdepth="4"?>
<?rfc symrefs="yes"?>
<?rfc sortrefs="yes"?>
<rfc submissionType="IETF">
<front>
  <title>The Holy Hand Grenade of Antioch</title>
  <author fullname="Arthur Pendragon" surname="Pendragon"/>
  <date day="14" month="December" year="2017"/>
  <workgroup>silly</workgroup>

</front><middle>
<section anchor="xyz" title="Hello"><t>Hello</t>
<t>
  <list style="symbols">
    <t>a Section 2.3 of <xref target="RFC2119">See internet draft subsection</xref></t>
    <t>b <xref target="I-D.abarth-cake"/></t>
    <t>c <xref target="xyz" format="counter">xyzzy</xref></t>
    <t>d <xref target="biblio"/></t>
    <t>e <xref target="AsciiDoc">AsciiDoctor</xref></t>
    <t>f <xref target="mathrefs"/></t>
  </list>
</t>
<section anchor="biblio" title="Biblio">
  <t>See biblio</t>
</section></section>
</middle><back>
<references title="Normative References">&RFC2119;
<reference anchor="AsciiDoc" target="http://www.methods.co.nz/asciidoc/">
<front>
<title>AsciiDoc: Text based document generation</title>
<author initials="S." surname="Rackham" fullname="Stuart Rackham"><organization/></author>
<date year="2013" month="November"/>
</front>
</reference>

</references>
<references title="Informative References">&I-D.abarth-cake;

<referencegroup anchor="mathrefs">
<reference anchor="AsciiMathML" target="http://asciimath.org">
<front>
  <title>AsciiMath is an easy-to-write markup language for mathematics.</title>
<author/>
<date year="2017" month="November"/>
</front>
</reference>


<reference anchor="MathJax" target="https://www.mathjax.org">
<front>
  <title>MathJax: A JavaScript display engine for mathematics that works in all browsers.</title>
<author/>
<date year="2017" month="November"/>
</front>
</reference>

</referencegroup>
</references>
</back>
</rfc>
````


v3 output:
````
<?xml version="1.0" encoding="US-ASCII"?>
<!DOCTYPE rfc SYSTEM "rfc2629.dtd">
<?rfc strict="yes"?>
<?rfc compact="yes"?>
<?rfc subcompact="no"?>
<?rfc toc="yes"?>
<?rfc tocdepth="4"?>
<?rfc symrefs="yes"?>
<?rfc sortrefs="yes"?>
<rfc xmlns:xi="http://www.w3.org/2001/XInclude" submissionType="IETF" prepTime="2017-12-13T22:05:49Z" version="3">
<front>
  <title>The Holy Hand Grenade of Antioch</title>
  <author fullname="Arthur Pendragon" surname="Pendragon"/>
  <date day="14" month="December" year="2017"/>
  <workgroup>silly</workgroup>

</front><middle>
<section anchor="xyz" numbered="false"><name>Hello</name><t>Hello</t>
<ul>
  <li>a <relref section="2.3" displayFormat="of" target="RFC2119">See internet draft subsection</relref></li>
  <li>b <xref target="I-D.abarth-cake"/></li>
  <li>c <xref format="counter" target="xyz">xyzzy</xref></li>
  <li>d <xref target="biblio"/></li>
  <li>e <xref target="AsciiDoc">AsciiDoctor</xref></li>
  <li>f <xref target="mathrefs"/></li>
</ul>
<section anchor="biblio" numbered="false">
  <name>Biblio</name>
  <t>See biblio</t>
</section></section>
</middle><back>
<references anchor="_normative_references"><xi:include href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml" parse="text"/>
<reference anchor="AsciiDoc" target="http://www.methods.co.nz/asciidoc/">
<front>
<title>AsciiDoc: Text based document generation</title>
<author initials="S." surname="Rackham" fullname="Stuart Rackham"><organization/></author>
<date year="2013" month="November"/>
</front>
</reference>

</references>
<references anchor="_informative_references"><xi:include href="https://xml2rfc.tools.ietf.org/public/rfc/bibxml3//reference.I-D.draft-abarth-cake-00.xml" parse="text"/>

<referencegroup anchor="mathrefs">
<reference anchor="AsciiMathML" target="http://asciimath.org">
<front>
  <title>AsciiMath is an easy-to-write markup language for mathematics.</title>
<author/>
<date year="2017" month="November"/>
</front>
</reference>


<reference anchor="MathJax" target="https://www.mathjax.org">
<front>
  <title>MathJax: A JavaScript display engine for mathematics that works in all browsers.</title>
<author/>
<date year="2017" month="November"/>
</front>
</reference>

</referencegroup>
</references>
</back>
</rfc>
````

**Comment by opoudjis** [comment]
Added spec/examples/biblio-insert-v2.adoc, spec/examples/biblio-insert-v3.adoc as examples of the approach.

**Comment by ronaldtse** [comment]
In terms of flow, it feels to me that
* `asciidoctor-bibliography` should deal with all the bibliography reading (e.g.,  the BibXML database, as a single file or as separate files in a directory) and reference grouping
* `asciidoctor-rfc` should ask the bibliography gem for the sorted set of BibXML data in reference groups
* `asciidoctor-rfc` should insert the references to the resulting XML because it is in charge of the resulting RFC XML document

We really don't want to make a one-line JSON though... In fact, asciidoctor supports a "document preamble" that occurs before the document header, it could parse JSON or YAML. 

Perhaps we can ping Julian about xml2rfc's support of multiple reference groups?

**Comment by opoudjis** [comment]
> Perhaps we can ping Julian about xml2rfc's support of multiple reference groups?

That would be good. I'll look into document preamble.

Can we have asciidoctor-rfc accept both RFC XML and BibXML as input formats? If so, then when BibXML is specified, it will invoke the asciidoctor-bibliography.

The current implementation is doing grouping into normative and informative anyway within asciidoctor-rfc, and I don't see that as a bad thing. 

It seems to me that the only remaining work is to have asciidoctor-bibliography do BibXML to RFC XML conversion, and then let asciidoctor-rfc invoke it.

Do you want this to be the preferred workflow, or do you want to keep the existing preprocessing of citations by the current asciidoctor-bibliography gem as an option?

**Comment by ronaldtse** [comment]
That’s why maybe there should be a better format for describing these things...

Or maybe we can make a PR to override this behavior in asciidoctor, but it would be quite difficult given the parsing structure of it.

**Comment by ronaldtse** [comment]
And my answer to your previous question is affirmative. Thanks!

**Comment by opoudjis** [comment]
Documented new behaviour, merged into master.

**Comment by opoudjis** [comment]
This ticket is open pending work on Asciidoctor-Biblio as a converter from BibXML to XML RFC.

**Comment by opoudjis** [comment]
@ronaldtse, given everything else I am doing, I would rather someone else still do the BibXml to RFC XML conversion. Closing this ticket since that is really an autonomous piece of work.
