### ISSUE TITLE
Support automatic citations to RFCs / I-Ds like MMark

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#9]
We should support automatic citations like MMark. 

https://github.com/miekg/mmark/wiki/Syntax#citations

* `[@RFC1234]` => points to `RFC 1234`
* `[@I-D.blah#06]` => points to `draft-blah-06`
* `[@I-D.hello]` => points to `draft-hello-xx` where `xx` is the latest version.

**Comment by ronaldtse** [comment]
@paolobrasolin should this be done in asciidoctor-bibliography? Or an "addon" to it?

**Comment by ronaldtse** [comment]
And output in this format https://tools.ietf.org/html/rfc7749#section-2.30

**Comment by paolobrasolin** [comment]
We can definitely support the syntax of `asciidoctor-bibliography`; matchers and data structures are already in place, so it should be relatively straightforward to output in RFC.

**Comment by ronaldtse** [comment]
Looks like we should support this syntax and output:

`cite:[@RFC1234]`
* citation reference => `<xref target="RFC1234"/>`
* add in `<references>`: `<?rfc include="https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.1234.xml"?>`

`cite:[@I-D.xxx-yyy-zzz]`
* citation reference => `<xref target="I-D.xxx-yyy-zzz"/>`
* add in `<references>`: `<?rfc include="https://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.xxx-yyy-zzz.xml"?>`

`cite:[@I-D.xxx-yyy-zzz#11]`
* citation reference => `<xref target="I-D.xxx-yyy-zzz-11"/>`
* add in `<references>`: `<?rfc include="https://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.xxx-yyy-zzz-11.xml"?>`

Then `xml2rfc` will automatically fetch these references.

@paolobrasolin maybe we can also provide a shorter syntax for `cite:[]`, such as MMark's `[@RFC1234]` or Kramdown's `{{@RFC1234}}`?

**Comment by ronaldtse** [comment]
Actually @paolobrasolin we can make this syntax work?
* `<<?RFC1234>>` (informative)
* `<<!RFC1234>>` (normative)
* `<<-RFC1234>>` (suppress in references)

**Comment by opoudjis** [comment]
Implemented with `cite:norm[]` and `cite:info[]`
