### ISSUE TITLE
CR before literal/sourcecode

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-rfc#95]
https://datatracker.ietf.org/doc/conflict-review-ribose-asciirfc/ballot/

> Adam Roach No Objection
> Comment (2018-03-30)
> I think the answer is correct.

> On a quick skim, I note that the document itself -- presumably produced by the toolchain it  describes -- appears to have all leading spaces stripped from artwork and code, resulting in varying degrees of damage to readability. I would hope that the popularization of this toolchain does not lead to documents with similar defects showing up for approval in the IESG stream, and would strongly recommend that the authors debug this aspect of the toolchain prior to publication of this document.

**Comment by ronaldtse** [comment]
Thanks for posting this @opoudjis .

**Comment by ronaldtse** [comment]
@opoudjis I just want to confirm that the issue is about line length exceeding limits (we have some https links that are beyond 72 chars) or is it because of stripping leading spaces?

**Comment by opoudjis** [comment]
It's the latter

**Comment by ronaldtse** [comment]
Cool, thanks.

**Comment by opoudjis** [comment]
The stripping is being done by xml2rfc; the XML leaves the initial spaces intact.

Unfortunately, we are stuck in the ecosystem of xml2rfc, and I presume the stripping is happening because we have not injected CDATA, like they have in their canonical examples. Trying that out.

**Comment by opoudjis** [comment]
I'm making artwork be wrapped in CDATA, which is what they do; but this looks to be an artefact of the folding script. Adjusting both.
