### ISSUE TITLE
Automatic section referencing overrides explicit references

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#96]
```adoc
[[hash_whirlpool]]
=== WHIRLPOOL

The WHIRLPOOL hash function is defined in <<WHIRLPOOL>>.

This section should actually be referenced as <<hash_whirlpool>>.
...

[bibliography]
== Informative References
++++
<reference anchor='WHIRLPOOL' target='http://www.larc.usp.br/~pbarreto/WhirlpoolPage.html'>
...
++++
```

You'll find out that both references point to <<hash_whirlpool>>. Basically, the automatic reference kills the external reference, but that's wrong.

**Comment by opoudjis** [comment]
Looks like this is built in to Asciidoctor. Looking to see if this can be overridden at all.

**Comment by opoudjis** [comment]
This is indeed built-in Asciidoctor behaviour: see https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/substitutors.rb, sub_inline_xrefs() (line 1008ff).

If the identifier in the crossreference is found as an anchor, it will crossreference to the anchor.
If it is not found (line 1079), it will attempt a match to a title.

The problem with the external references is, Asciidoctor never sees them at all: they are opaque XML to it. So the title match does indeed take priority over the external reference.

I suppose this could be solved by some sort of preprocessing, whereby I go through the opaque XML and extract out all anchor attributes, and create dummy Asciidoctor anchors, which I get rid of later. That's pretty revolting, though, for what is clearly an edge case—and one that users should merely be alerted about instead. (Don't use anchors in references that look like section titles.)

Apparently this can also be averted by setting  doc.compat_mode or Compliance.natural_xrefs = false, which disables matching crossreferences by title (line 1073). That is done through Asciidoctor::Compliance.natural_xrefs = false ; see https://github.com/asciidoctor/asciidoctor/issues/2405 (and Asciidoctor's longstanding tradition of not really documenting their code in the user manual).

Will attempt to set this in Asciidoctor-rfc base tomorrow. The test code seems to indicate it will work: cf https://github.com/asciidoctor/asciidoctor/blob/master/benchmark/benchmark.rb , line 74

**Comment by opoudjis** [comment]
The Asciidoctor::Compliance.natural_xrefs configuration is coming in Asciidoctor 1.5.7; 1.5.6.2 got released a month ago. The source code is there in git, but I'd suggest we leave this as a known issue, and reactivate it when 1.5.7 is released.

**Comment by ronaldtse** [comment]
Thanks @opoudjis , that would be an acceptable solution. Hope it gets released soon.

**Comment by ronaldtse** [comment]
I have to add that the real reason this happens is that citations are mixing with cross-references, which is not entirely correct.

**Comment by opoudjis** [comment]
Documented in Readme. I would be surprised if it is released before the end of the year.

**Comment by ronaldtse** [comment]
Got it. Thanks!

**Comment by opoudjis** [comment]
https://github.com/asciidoctor/asciidoctor/releases/tag/v1.5.7 is out rather sooner than I'd thought
